FROM python:latest

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir requests

ADD is_functionnal_test.py ./

EXPOSE 8080

ENV LOG 1

VOLUME project_volume

CMD python3 is_functionnal_test.py
