FROM debian:latest

# ADD api.py fraud_model.pkl ML_model.py input_data_model.py requirements.txt ./

ADD . .

RUN apt-get update && apt-get install python3-pip -y && pip3 install fastapi && pip3 install -r requirements.txt

EXPOSE 8080

CMD python3 api.py
